### ISSUE TITLE
Installation via pip fails because README.md is not in the tarball

### ISSUE THREAD

**Issue by iliana** [oisinmulvihill/stomper#3]
```
(datagrepper)[ianweller@cavanagh build]$ pip install stomper
Downloading/unpacking stomper
  Downloading stomper-0.2.6.tar.gz
  Running setup.py egg_info for package stomper
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ianweller/.virtualenvs/datagrepper/build/stomper/setup.py", line 35, in <module>
        fd = file("README.md")
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ianweller/.virtualenvs/datagrepper/build/stomper/setup.py", line 35, in <module>

    fd = file("README.md")

IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by dlparker** [comment]
I don't think this is fixed. I just did a pip install stomper and got the same error.
